In [1]:
import numpy as np
import ase
from ase.visualize import view

In [2]:
def reduce_cell(obj):
    pos = obj.get_positions()
    xmax = max(pos[:,0])
    ymax = max(pos[:,1])
    zmax = max(pos[:,2])
    cell = np.diag((xmax,ymax,zmax))
    obj.set_cell(cell)

In [5]:
struct = ase.Atoms('C')
struct.pop(0)
n = 10000 # number of lines to read
lx = 50
ly = 50
lz = 50
cell = np.diag((lx,ly,lz))
pos = np.zeros((n,3))
sym = np.zeros(n)
f = open('Dump_files/dump0','r')
for i in np.arange(9):
    line = f.readline()
    if i == 3:
        N = int(line) # number of atoms in list
    if i == 5:
        line = line.split(' ')
        xmin = float(line[0])
        xmax = float(line[1])
    if i == 6:
        line = line.split(' ')
        ymin = float(line[0])
        ymax = float(line[1])
    if i == 7:
        line = line.split(' ')
        zmin = float(line[0])
        zmax = float(line[1])
dx = xmax-xmin
dy = ymax-ymin
dz = zmax-zmin
full_cell = np.diag((dx,dy,dz))
trans_pos = [dx/2,dy/2,dz/2]
#trans_pos = [0,0,0]
for i in np.arange(N):
    if (i%100000)==0:
        print(i)
    list = f.readline()[:-1].split(' ')
    list = [float(i) for i in list]
    pos_temp = np.array(list[2:5])
    pos_temp = np.matmul(full_cell,pos_temp) # from fractional coord to Angstr.
    #pos_temp = [pos_temp[j]-trans_pos[j] for j in range(3)]
    np.subtract(pos_temp,trans_pos,out=pos_temp)
    sym_temp = list[1]
    if pos_temp[0]>=0 and pos_temp[1]>=0 and pos_temp[2]>=0:
        if pos_temp[0]<lx and pos_temp[1]<ly and pos_temp[2]<lz:
            struct.append(ase.atom.Atom(sym_temp,pos_temp))
            #pos_temp=pos_temp
f.close()
#cell = [[dx,0,0],[0,dy,0],[0,0,dz]]
struct.set_cell(cell)
#reduce_cell(struct)
print(struct.get_cell())
print(len(struct.get_positions()))
view(struct)

0
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
[[50.  0.  0.]
 [ 0. 50.  0.]
 [ 0.  0. 50.]]
7207
